[server]
enableStaticServing = true
staticDir = "media"
port = 8501
headless = true

[theme]
base = "dark"
primaryColor = "#00FFFF"
backgroundColor = "#000011"
secondaryBackgroundColor = "#001122"
textColor = "#FFFFFF"

[browser]
gatherUsageStats = false
