[server]
enableStaticServing = true
port = 8501
headless = true
maxUploadSize = 10

[theme]
base = "dark"
primaryColor = "#00FFFF"
backgroundColor = "#000011"
secondaryBackgroundColor = "#001122"
textColor = "#FFFFFF"
font = "monospace"

[browser]
gatherUsageStats = false

[client]
caching = true
displayEnabled = true

[logger]
level = "info"
